services:
  - type: web
    name: mi-inventario
    runtime: image
    repo: https://github.com/k3a77666-rgb/LOGIN
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: ""
    startCommand: "dotnet LOGIN.dll"